name: Trigger auto deployment for gateway

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '/services/gateway/**'
    - '.github/workflows/gateway-AutoDeployTrigger-29761246-ae57-4588-b4b0-c12a6c696374.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.GATEWAY_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.GATEWAY_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.GATEWAY_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/services/gateway 
          registryUrl: docker.io
          registryUsername: ${{ secrets.GATEWAY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.GATEWAY_REGISTRY_PASSWORD }}
          containerAppName: gateway
          resourceGroup: Wallmarkt
          imageToBuild: rensvangiersbergen/gateway:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


